# Generated by Django 5.2.5 on 2025-08-25 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'مادة',
                'verbose_name_plural': 'مواد',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(choices=[(1, 'السنة الأولى'), (2, 'السنة الثانية')])),
            ],
            options={
                'verbose_name': 'سنة',
                'verbose_name_plural': 'سنوات',
                'unique_together': {('number',)},
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(choices=[(1, 'الفصل الأول'), (2, 'الفصل الثاني')])),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='edu.year')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'فصول',
                'unique_together': {('year', 'number')},
            },
        ),
        migrations.CreateModel(
            name='SubjectOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='edu.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='edu.term')),
            ],
            options={
                'verbose_name': 'مادة في فصل',
                'verbose_name_plural': 'مواد الفصل',
                'unique_together': {('term', 'subject')},
            },
        ),
    ]
