# Generated by Django 5.2.5 on 2025-08-25 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الدرس')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='الترتيب')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='edu.subjectoffering')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'دروس',
                'ordering': ['order', 'id'],
                'unique_together': {('offering', 'title')},
            },
        ),
        migrations.CreateModel(
            name='LessonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, verbose_name='المحتوى النصّي')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='edu.lesson')),
            ],
            options={
                'verbose_name': 'محتوى الدرس (نص)',
                'verbose_name_plural': 'محتوى الدروس (نص)',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص السؤال')),
                ('section', models.CharField(choices=[('FIRST', 'القسم الأول'), ('SECOND', 'القسم الثاني'), ('FULL', 'كامل القسم')], default='FULL', max_length=10, verbose_name='القسم')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='edu.lesson')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'أسئلة',
            },
        ),
    ]
