# Generated by Django 5.2.5 on 2025-08-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_lesson_lessoncontent_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice1',
            field=models.CharField(default='—', max_length=300, verbose_name='الخيار 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='choice2',
            field=models.CharField(default='—', max_length=300, verbose_name='الخيار 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='choice3',
            field=models.CharField(default=1, max_length=300, verbose_name='الخيار 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='correct',
            field=models.PositiveSmallIntegerField(choices=[(1, 'الخيار 1'), (2, 'الخيار 2'), (3, 'الخيار 3')], default=1, verbose_name='الإجابة الصحيحة'),
        ),
    ]
