# Generated by Django 5.2.5 on 2025-08-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_question_choice1_question_choice2_question_choice3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice1',
            field=models.CharField(default='—', max_length=300, verbose_name='الخيار 1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice2',
            field=models.CharField(default='—', max_length=300, verbose_name='الخيار 2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice3',
            field=models.CharField(default='—', max_length=300, verbose_name='الخيار 3'),
        ),
    ]
