# Generated by Django 5.2.5 on 2025-08-25 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_alter_question_choice1_alter_question_choice2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'الاثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت'), (6, 'الأحد')])),
                ('lecture_no', models.PositiveSmallIntegerField(blank=True, help_text='اختياري: رقم المحاضرة في نفس اليوم', null=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='edu.subjectoffering')),
            ],
            options={
                'verbose_name': 'جدول مادة (يوم)',
                'verbose_name_plural': 'جدول مواد (أيام)',
            },
        ),
    ]
