# Generated by Django 5.2.5 on 2025-08-31 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_week_weeklyquiz_weeklyquestion_weeklyattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyquestion',
            name='choice1',
        ),
        migrations.RemoveField(
            model_name='weeklyquestion',
            name='choice2',
        ),
        migrations.RemoveField(
            model_name='weeklyquestion',
            name='choice3',
        ),
        migrations.RemoveField(
            model_name='weeklyquestion',
            name='correct',
        ),
        migrations.AddField(
            model_name='weeklyquestion',
            name='correct_bool',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyquestion',
            name='qtype',
            field=models.CharField(choices=[('MCQ', 'اختيارات'), ('TF', 'صح/خطأ')], default='MCQ', max_length=3),
        ),
        migrations.CreateModel(
            name='WeeklyChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='edu.weeklyquestion')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='WeeklyAttempt',
        ),
    ]
